'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace ServiceProfilePic
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceProfilePicSoap", [Namespace]:="http://tempuri.org/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Object()))>  _
    Partial Public Class ServiceProfilePic
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ChekConnectionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebAppUserSetProfilePictureOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebAppUserGetProfilePictureOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestWriteFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TestReadFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebAppUserGetLabelOperationCompleted As System.Threading.SendOrPostCallback
        
        Private WebAppUserCreateLabelOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FunctionGetFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FunctionCreateFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FunctionDeleteFileOperationCompleted As System.Threading.SendOrPostCallback
        
        Private FunctionGetFileInfoListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ReportWeb.My.MySettings.Default.ReportWeb_ServiceProfilePic_ServiceProfilePic
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ChekConnectionCompleted As ChekConnectionCompletedEventHandler
        
        '''<remarks/>
        Public Event WebAppUserSetProfilePictureCompleted As WebAppUserSetProfilePictureCompletedEventHandler
        
        '''<remarks/>
        Public Event WebAppUserGetProfilePictureCompleted As WebAppUserGetProfilePictureCompletedEventHandler
        
        '''<remarks/>
        Public Event TestWriteFileCompleted As TestWriteFileCompletedEventHandler
        
        '''<remarks/>
        Public Event TestReadFileCompleted As TestReadFileCompletedEventHandler
        
        '''<remarks/>
        Public Event WebAppUserGetLabelCompleted As WebAppUserGetLabelCompletedEventHandler
        
        '''<remarks/>
        Public Event WebAppUserCreateLabelCompleted As WebAppUserCreateLabelCompletedEventHandler
        
        '''<remarks/>
        Public Event FunctionGetFileCompleted As FunctionGetFileCompletedEventHandler
        
        '''<remarks/>
        Public Event FunctionCreateFileCompleted As FunctionCreateFileCompletedEventHandler
        
        '''<remarks/>
        Public Event FunctionDeleteFileCompleted As FunctionDeleteFileCompletedEventHandler
        
        '''<remarks/>
        Public Event FunctionGetFileInfoListCompleted As FunctionGetFileInfoListCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ChekConnection", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ChekConnection() As String
            Dim results() As Object = Me.Invoke("ChekConnection", New Object(-1) {})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ChekConnectionAsync()
            Me.ChekConnectionAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ChekConnectionAsync(ByVal userState As Object)
            If (Me.ChekConnectionOperationCompleted Is Nothing) Then
                Me.ChekConnectionOperationCompleted = AddressOf Me.OnChekConnectionOperationCompleted
            End If
            Me.InvokeAsync("ChekConnection", New Object(-1) {}, Me.ChekConnectionOperationCompleted, userState)
        End Sub
        
        Private Sub OnChekConnectionOperationCompleted(ByVal arg As Object)
            If (Not (Me.ChekConnectionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ChekConnectionCompleted(Me, New ChekConnectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebAppUserSetProfilePicture", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebAppUserSetProfilePicture(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object) As Object()
            Dim results() As Object = Me.Invoke("WebAppUserSetProfilePicture", New Object() {AppName, AppVersion, Param})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebAppUserSetProfilePictureAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object)
            Me.WebAppUserSetProfilePictureAsync(AppName, AppVersion, Param, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebAppUserSetProfilePictureAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByVal userState As Object)
            If (Me.WebAppUserSetProfilePictureOperationCompleted Is Nothing) Then
                Me.WebAppUserSetProfilePictureOperationCompleted = AddressOf Me.OnWebAppUserSetProfilePictureOperationCompleted
            End If
            Me.InvokeAsync("WebAppUserSetProfilePicture", New Object() {AppName, AppVersion, Param}, Me.WebAppUserSetProfilePictureOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebAppUserSetProfilePictureOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebAppUserSetProfilePictureCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebAppUserSetProfilePictureCompleted(Me, New WebAppUserSetProfilePictureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebAppUserGetProfilePicture", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebAppUserGetProfilePicture(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object) As Object()
            Dim results() As Object = Me.Invoke("WebAppUserGetProfilePicture", New Object() {AppName, AppVersion, Param})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebAppUserGetProfilePictureAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object)
            Me.WebAppUserGetProfilePictureAsync(AppName, AppVersion, Param, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebAppUserGetProfilePictureAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByVal userState As Object)
            If (Me.WebAppUserGetProfilePictureOperationCompleted Is Nothing) Then
                Me.WebAppUserGetProfilePictureOperationCompleted = AddressOf Me.OnWebAppUserGetProfilePictureOperationCompleted
            End If
            Me.InvokeAsync("WebAppUserGetProfilePicture", New Object() {AppName, AppVersion, Param}, Me.WebAppUserGetProfilePictureOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebAppUserGetProfilePictureOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebAppUserGetProfilePictureCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebAppUserGetProfilePictureCompleted(Me, New WebAppUserGetProfilePictureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestWriteFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub TestWriteFile()
            Me.Invoke("TestWriteFile", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestWriteFileAsync()
            Me.TestWriteFileAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestWriteFileAsync(ByVal userState As Object)
            If (Me.TestWriteFileOperationCompleted Is Nothing) Then
                Me.TestWriteFileOperationCompleted = AddressOf Me.OnTestWriteFileOperationCompleted
            End If
            Me.InvokeAsync("TestWriteFile", New Object(-1) {}, Me.TestWriteFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestWriteFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestWriteFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestWriteFileCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TestReadFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub TestReadFile()
            Me.Invoke("TestReadFile", New Object(-1) {})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestReadFileAsync()
            Me.TestReadFileAsync(Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TestReadFileAsync(ByVal userState As Object)
            If (Me.TestReadFileOperationCompleted Is Nothing) Then
                Me.TestReadFileOperationCompleted = AddressOf Me.OnTestReadFileOperationCompleted
            End If
            Me.InvokeAsync("TestReadFile", New Object(-1) {}, Me.TestReadFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnTestReadFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.TestReadFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TestReadFileCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebAppUserGetLabel", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebAppUserGetLabel(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object) As Object()
            Dim results() As Object = Me.Invoke("WebAppUserGetLabel", New Object() {AppName, AppVersion, Param})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebAppUserGetLabelAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object)
            Me.WebAppUserGetLabelAsync(AppName, AppVersion, Param, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebAppUserGetLabelAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByVal userState As Object)
            If (Me.WebAppUserGetLabelOperationCompleted Is Nothing) Then
                Me.WebAppUserGetLabelOperationCompleted = AddressOf Me.OnWebAppUserGetLabelOperationCompleted
            End If
            Me.InvokeAsync("WebAppUserGetLabel", New Object() {AppName, AppVersion, Param}, Me.WebAppUserGetLabelOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebAppUserGetLabelOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebAppUserGetLabelCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebAppUserGetLabelCompleted(Me, New WebAppUserGetLabelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/WebAppUserCreateLabel", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function WebAppUserCreateLabel(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object) As Object()
            Dim results() As Object = Me.Invoke("WebAppUserCreateLabel", New Object() {AppName, AppVersion, Param})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub WebAppUserCreateLabelAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object)
            Me.WebAppUserCreateLabelAsync(AppName, AppVersion, Param, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub WebAppUserCreateLabelAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByVal userState As Object)
            If (Me.WebAppUserCreateLabelOperationCompleted Is Nothing) Then
                Me.WebAppUserCreateLabelOperationCompleted = AddressOf Me.OnWebAppUserCreateLabelOperationCompleted
            End If
            Me.InvokeAsync("WebAppUserCreateLabel", New Object() {AppName, AppVersion, Param}, Me.WebAppUserCreateLabelOperationCompleted, userState)
        End Sub
        
        Private Sub OnWebAppUserCreateLabelOperationCompleted(ByVal arg As Object)
            If (Not (Me.WebAppUserCreateLabelCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent WebAppUserCreateLabelCompleted(Me, New WebAppUserCreateLabelCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FunctionGetFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FunctionGetFile(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object) As Object()
            Dim results() As Object = Me.Invoke("FunctionGetFile", New Object() {AppName, AppVersion, Param})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub FunctionGetFileAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object)
            Me.FunctionGetFileAsync(AppName, AppVersion, Param, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FunctionGetFileAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByVal userState As Object)
            If (Me.FunctionGetFileOperationCompleted Is Nothing) Then
                Me.FunctionGetFileOperationCompleted = AddressOf Me.OnFunctionGetFileOperationCompleted
            End If
            Me.InvokeAsync("FunctionGetFile", New Object() {AppName, AppVersion, Param}, Me.FunctionGetFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnFunctionGetFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.FunctionGetFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FunctionGetFileCompleted(Me, New FunctionGetFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FunctionCreateFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FunctionCreateFile(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object) As Object()
            Dim results() As Object = Me.Invoke("FunctionCreateFile", New Object() {AppName, AppVersion, Param})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub FunctionCreateFileAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object)
            Me.FunctionCreateFileAsync(AppName, AppVersion, Param, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FunctionCreateFileAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByVal userState As Object)
            If (Me.FunctionCreateFileOperationCompleted Is Nothing) Then
                Me.FunctionCreateFileOperationCompleted = AddressOf Me.OnFunctionCreateFileOperationCompleted
            End If
            Me.InvokeAsync("FunctionCreateFile", New Object() {AppName, AppVersion, Param}, Me.FunctionCreateFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnFunctionCreateFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.FunctionCreateFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FunctionCreateFileCompleted(Me, New FunctionCreateFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FunctionDeleteFile", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FunctionDeleteFile(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object) As Object()
            Dim results() As Object = Me.Invoke("FunctionDeleteFile", New Object() {AppName, AppVersion, Param})
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub FunctionDeleteFileAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object)
            Me.FunctionDeleteFileAsync(AppName, AppVersion, Param, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FunctionDeleteFileAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByVal userState As Object)
            If (Me.FunctionDeleteFileOperationCompleted Is Nothing) Then
                Me.FunctionDeleteFileOperationCompleted = AddressOf Me.OnFunctionDeleteFileOperationCompleted
            End If
            Me.InvokeAsync("FunctionDeleteFile", New Object() {AppName, AppVersion, Param}, Me.FunctionDeleteFileOperationCompleted, userState)
        End Sub
        
        Private Sub OnFunctionDeleteFileOperationCompleted(ByVal arg As Object)
            If (Not (Me.FunctionDeleteFileCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FunctionDeleteFileCompleted(Me, New FunctionDeleteFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FunctionGetFileInfoList", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function FunctionGetFileInfoList(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByRef dsData As System.Data.DataSet) As Object()
            Dim results() As Object = Me.Invoke("FunctionGetFileInfoList", New Object() {AppName, AppVersion, Param, dsData})
            dsData = CType(results(1),System.Data.DataSet)
            Return CType(results(0),Object())
        End Function
        
        '''<remarks/>
        Public Overloads Sub FunctionGetFileInfoListAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByVal dsData As System.Data.DataSet)
            Me.FunctionGetFileInfoListAsync(AppName, AppVersion, Param, dsData, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub FunctionGetFileInfoListAsync(ByVal AppName As String, ByVal AppVersion As String, ByVal Param() As Object, ByVal dsData As System.Data.DataSet, ByVal userState As Object)
            If (Me.FunctionGetFileInfoListOperationCompleted Is Nothing) Then
                Me.FunctionGetFileInfoListOperationCompleted = AddressOf Me.OnFunctionGetFileInfoListOperationCompleted
            End If
            Me.InvokeAsync("FunctionGetFileInfoList", New Object() {AppName, AppVersion, Param, dsData}, Me.FunctionGetFileInfoListOperationCompleted, userState)
        End Sub
        
        Private Sub OnFunctionGetFileInfoListOperationCompleted(ByVal arg As Object)
            If (Not (Me.FunctionGetFileInfoListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent FunctionGetFileInfoListCompleted(Me, New FunctionGetFileInfoListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub ChekConnectionCompletedEventHandler(ByVal sender As Object, ByVal e As ChekConnectionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ChekConnectionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebAppUserSetProfilePictureCompletedEventHandler(ByVal sender As Object, ByVal e As WebAppUserSetProfilePictureCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebAppUserSetProfilePictureCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebAppUserGetProfilePictureCompletedEventHandler(ByVal sender As Object, ByVal e As WebAppUserGetProfilePictureCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebAppUserGetProfilePictureCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub TestWriteFileCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub TestReadFileCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebAppUserGetLabelCompletedEventHandler(ByVal sender As Object, ByVal e As WebAppUserGetLabelCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebAppUserGetLabelCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub WebAppUserCreateLabelCompletedEventHandler(ByVal sender As Object, ByVal e As WebAppUserCreateLabelCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class WebAppUserCreateLabelCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub FunctionGetFileCompletedEventHandler(ByVal sender As Object, ByVal e As FunctionGetFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FunctionGetFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub FunctionCreateFileCompletedEventHandler(ByVal sender As Object, ByVal e As FunctionCreateFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FunctionCreateFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub FunctionDeleteFileCompletedEventHandler(ByVal sender As Object, ByVal e As FunctionDeleteFileCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FunctionDeleteFileCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")>  _
    Public Delegate Sub FunctionGetFileInfoListCompletedEventHandler(ByVal sender As Object, ByVal e As FunctionGetFileInfoListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class FunctionGetFileInfoListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Object()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Object())
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property dsData() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
