'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class QueryTools

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''lblJudul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJudul As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SelectDB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SelectDB As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDatabase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDatabase As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblQuery As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtQuery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuery As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BtnExecute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnExecute As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnNewTab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnNewTab As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSelect As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnConcat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConcat As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnGroupConcat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGroupConcat As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnReplace control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnReplace As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnAddTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAddTime As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnUpdTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnUpdTime As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnTrackNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnTrackNum As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnOrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnOrderNo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnAddInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAddInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCode As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLog As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnFrom As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnInnerJoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnInnerJoin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnLeftJoin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLeftJoin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnTransaction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnTransaction As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnTracking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnTracking As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnTrcHist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnTrcHist As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnTrcDlvrInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnTrcDlvrInfo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnAutoOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAutoOrder As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnAutoOrdTrc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAutoOrdTrc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnAutoOrdTrcHis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAutoOrdTrcHis As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnAutoOrdCallback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAutoOrdCallback As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnTracelog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnTracelog As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnReqResLog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnReqResLog As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnAccount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAccount As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnIdmStore control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnIdmStore As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnMstLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnMstLogin As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnWhere control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnWhere As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnAnd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAnd As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnOr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnOr As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCurdateActInAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCurdateActInAct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnEquals control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEquals As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnLike control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLike As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnParenthesis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnParenthesis As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnDoubleQuote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDoubleQuote As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCurdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCurdate As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnGroupBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnGroupBy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnOrderBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnOrderBy As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDesc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnLimit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLimit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnShowTbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnShowTbl As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCreateTbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCreateTbl As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnShowProc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnShowProc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnCreateProc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCreateProc As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnDBDev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDBDev As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnTrcBalikanStaInWhoIn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnTrcBalikanStaInWhoIn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnConsServiceEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConsServiceEdit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnClear As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnDownload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDownload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnShowSlave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnShowSlave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtResult control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResult As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TrRowsCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrRowsCount As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblCtr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCtr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''TrData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TrData As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblData As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvData As Global.System.Web.UI.WebControls.GridView
End Class
